sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    password: root
    database: 0

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8wyQ4GLfj7TDvNUXXc
    access-key-secret: Lnaz3Z1IrTd9M0zb60MHqIcAV1wyGh
    bucket-name: sky-itcast-ck

  wechat:
    appid: wx64093361b9de56b8
    secret: 057bc2b1b115b16fd931aa4b48fc0df5
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\ASDVG.pem
    notifyUrl: https://55d907af.r7.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://55d907af.r7.cpolar.cn/notify/refundSuccess
